import { Request, Response } from "express";
import { PRINTIFY_ERRORS } from "../config/printifyErrors";
import { validationResult } from "express-validator";
import type { IPrintifyService } from "../services/printifyService";
import type { IOrderService } from "../services/orderService";
import type { IEmailService } from "../services/emailService";
import { ShippingRatesRequestBody } from "../types/printifyShipping";
import { PrintifyOrderRequest } from "../types/printifyOrder";
import { sendError } from "../utils/sendError";
import crypto from "node:crypto";
import type { ParamsDictionary } from "express-serve-static-core";

/**
 * Request body for submitting a new Printify order.
 */
export type SubmitOrderBody = {
    /** Store identifier used to route to correct Printify config. */
    storeId: string;
    /** Order payload to submit to Printify. */
    order: PrintifyOrderRequest;
    /** Stripe payment intent ID associated with this order. */
    stripe_payment_id: string;
};

/**
 * Request body for retrieving order status by ID and customer email.
 */
export type GetOrderStatusBody = {
    /** External order number generated by our system. */
    orderId: string;
    /** Customer email used to look up the order. */
    email: string;
};

/**
 * Shape of the object returned by `createPrintifyController`.
 */
export type PrintifyController = ReturnType<typeof createPrintifyController>;
/**
 * Creates handlers for Printify-related endpoints.
 *
 * @param {IPrintifyService} printifyService - Service for Printify API operations.
 * @param {IOrderService} orderService - Service for persisting and querying orders.
 * @param {IEmailService} emailService - Service for sending order confirmation emails.
 * @returns {PrintifyController} Object with handler functions.
 */
export const createPrintifyController = (
    printifyService: IPrintifyService,
    orderService: IOrderService,
    emailService: IEmailService
) => {
    return {
        /**
         * Gets all Printify products for a given store.
         *
         * @see GET /printify/:id/products
         * @param {Request<{ id: string }>} req - Express request; params `{ id }` for store.
         * @param {Response} res - Express response object.
         * @returns {Promise<void>} Sends response via `res`; no return value.
         * @remarks On success: 200 with products. On validation error: 400 `{ errors }`. On server error: 500 `{ error }`.
         */
        getProducts: async (req: Request<{ id: string }>, res: Response) => {
            const errors = validationResult(req);
            if (!errors.isEmpty()) {
                    sendError(
                        res,
                        400,
                        errors.array().map((e) => String(e.msg))
                    );
                return;
            }
            try {
                const { id: storeId } = req.params;
                if (!storeId) {
                    sendError(res, 400, PRINTIFY_ERRORS.MISSING_STORE_ID);
                    return;
                }
                const products = await printifyService.getProducts(storeId);
                res.status(200).json(products);
                return;
            } catch (err) {
                console.error("Error in printifyController.getProducts", err);
                sendError(res, 500, PRINTIFY_ERRORS.FAILED_FETCH_PRODUCTS);
                return;
            }
        },

        /**
         * Gets Printify shipping options for a given store and order details.
         *
         * @see POST /printify/:id/shipping-options
         * @param {Request<{ id: string }, unknown, ShippingRatesRequestBody>} req - Express request; params `{ id }`, body `ShippingRatesRequestBody`.
         * @param {Response} res - Express response object.
         * @returns {Promise<void>} Sends response via `res`; no return value.
         * @remarks On success: 200 with options. On validation error: 400 `{ errors }`. On server error: 500 `{ error }`.
         */
        getShippingOptions: async (
            req: Request<{ id: string }, unknown, ShippingRatesRequestBody>,
            res: Response
        ) => {
            const errors = validationResult(req);
            if (!errors.isEmpty()) {
                    sendError(
                        res,
                        400,
                        errors.array().map((e) => String(e.msg))
                    );
                return;
            }
            try {
                const body = req.body;
                const { id: storeId } = req.params;
                if (!storeId) {
                    res.status(400).json({
                        error: "Missing store id in request parameters.",
                    });
                    return;
                }
                const options = await printifyService.getShippingRates(
                    storeId,
                    body
                );
                res.status(200).json(options);
                return;
            } catch (err) {
                console.error("Error fetching shipping rates:", err);
                sendError(res, 500, PRINTIFY_ERRORS.FAILED_SHIPPING_OPTIONS);
                return;
            }
        },

        /**
         * Submits a new order to Printify and saves it in the database.
         *
         * @see POST /printify/submit-order
         * @param {Request<ParamsDictionary, unknown, SubmitOrderBody>} req - Express request; body `{ storeId, order, stripe_payment_id }`.
         * @param {Response} res - Express response object.
         * @returns {Promise<void>} Sends response via `res`; no return value.
         * @remarks Uses Printify API to submit and persist orders; sends an email confirmation. On success: 201 `{ success, orderId, printifyOrderId }`. On validation error: 400 `{ errors }`. On server error: 500 `{ error }`.
         */
        submitOrder: async (
            req: Request<ParamsDictionary, unknown, SubmitOrderBody>,
            res: Response
        ) => {
            const errors = validationResult(req);
            if (!errors.isEmpty()) {
                    sendError(
                        res,
                        400,
                        errors.array().map((e) => String(e.msg))
                    );
                return;
            }

            const { storeId, order, stripe_payment_id } = req.body;

            try {
                const order_number = crypto.randomUUID();

                const newOrder = await orderService.saveOrder({
                    orderNumber: order_number,
                    storeId,
                    email: order.customer.email,
                    totalPrice: order.total_price,
                    currency: order.currency || "USD",
                    shippingMethod: order.shipping_method,
                    shippingCost: order.shipping_cost,
                    shippingAddress: order.customer.address,
                    items: order.line_items,
                    stripePaymentId: stripe_payment_id,
                    paymentStatus: "paid",
                    orderStatus: "pending",
                });
                console.log("Order saved in DB:", newOrder);

                // submit order to printify
                const printifyResponse = await printifyService.submitOrder(
                    storeId,
                    order_number,
                    order
                );
                console.log("Order submitted to Printify:", printifyResponse);

                // update database with printify order id
                await orderService.updatePrintifyOrderId(
                    order_number,
                    printifyResponse.id
                );

                const emailResult = await emailService.sendOrderConfirmation({
                    storeId,
                    to: order.customer.email,
                    orderNumber: order_number,
                    payload: {
                        address: order.customer.address,
                        items: order.line_items.map((li) => ({
                            title: li.metadata.title,
                            variant_label: li.metadata.variant_label,
                            quantity: li.quantity,
                            price: li.metadata.price,
                        })),
                        shippingMethod: order.shipping_method,
                        totalPrice: order.total_price,
                        currency: order.currency || "USD",
                    },
                });
                if (!emailResult.success) {
                    console.error("Order email failed:", emailResult.error);
                    // don’t throw; the order itself succeeded
                }

                res.status(201).json({
                    success: true,
                    orderId: newOrder.id,
                    printifyOrderId: printifyResponse.id,
                });
                return;
            } catch (err: unknown) {
                console.error("Error processing order:", err);
                sendError(res, 500, PRINTIFY_ERRORS.FAILED_PROCESS_ORDER);
                return;
            }
        },

        /**
         * Gets the status and details of a Printify order for a customer.
         *
         * @see POST /printify/order-status
         * @param {Request<ParamsDictionary, unknown, GetOrderStatusBody>} req - Express request; body `{ orderId, email }`.
         * @param {Response} res - Express response object.
         * @returns {Promise<void>} Sends response via `res`; no return value.
         * @remarks Handles order status retrieval. On success: 200 `{ success, order_status, tracking_number, ... }`. On validation error: 400 `{ errors }`. On not found: 404 `{ error }`. On server error: 500 `{ error }`.
         */
        getOrderStatus: async (
            req: Request<ParamsDictionary, unknown, GetOrderStatusBody>,
            res: Response
        ) => {
            const errors = validationResult(req);
            if (!errors.isEmpty()) {
                    sendError(
                        res,
                        400,
                        errors.array().map((e) => String(e.msg))
                    );
                return;
            }

            try {
                const { orderId, email } = req.body;
                const order = await orderService.getOrderByCustomer(
                    orderId,
                    email
                );

                if (!order) {
                    sendError(res, 404, PRINTIFY_ERRORS.ORDER_NOT_FOUND);
                    return;
                }
                if (!order.printify_order_id) {
                    sendError(res, 422, PRINTIFY_ERRORS.ORDER_NOT_FOUND);
                    return;
                }

                const printifyOrder = await printifyService.getOrder(
                    order.store_id,
                    order.printify_order_id
                );

                res.status(200).json({
                    success: true,
                    order_status: printifyOrder.status || "unknown",
                    tracking_number:
                        printifyOrder.shipments?.[0]?.number || null,
                    tracking_url: printifyOrder.shipments?.[0]?.url || null,
                    total_price: order.total_price, // DB value (customer's total price)
                    total_shipping: order.shipping_cost, // DB value (customer's shipping cost)
                    currency: order.currency,
                    created_at:
                        printifyOrder.created_at ?? new Date().toISOString(),

                    // Customer shipping details
                    customer: {
                        first_name: printifyOrder.address_to?.first_name || "",
                        last_name: printifyOrder.address_to?.last_name || "",
                        phone: printifyOrder.address_to?.phone || "",
                        country: printifyOrder.address_to?.country || "",
                        region: printifyOrder.address_to?.region || "",
                        city: printifyOrder.address_to?.city || "",
                        address1: printifyOrder.address_to?.address1 || "",
                        address2: printifyOrder.address_to?.address2 || "",
                        zip: printifyOrder.address_to?.zip || "",
                    },

                    // Ordered items
                    items: printifyOrder.line_items.map((item) => ({
                        product_id: item.product_id,
                        variant_id: item.variant_id,
                        quantity: item.quantity,
                        print_provider_id: item.print_provider_id,
                        price: item.metadata.price,
                        shipping_cost: item.shipping_cost ?? 0,
                        status: item.status,
                        title: item.metadata.title,
                        variant_label: item.metadata.variant_label,
                        sku: item.metadata.sku,
                        country: item.metadata.country ?? "Unknown",
                        sent_to_production_at:
                            item.sent_to_production_at ?? null,
                        fulfilled_at: item.fulfilled_at ?? null,
                    })),

                    // Order metadata
                    metadata: {
                        order_type: printifyOrder.metadata?.order_type || "N/A",
                        shop_order_id:
                            printifyOrder.metadata?.shop_order_id || "N/A",
                        shop_order_label:
                            printifyOrder.metadata?.shop_order_label || "N/A",
                        shop_fulfilled_at:
                            printifyOrder.metadata?.shop_fulfilled_at || null,
                    },

                    // Shipping details
                    shipping_method: printifyOrder.shipping_method,
                    is_printify_express:
                        printifyOrder.is_printify_express || false,
                    is_economy_shipping:
                        printifyOrder.is_economy_shipping || false,

                    // Tracking info
                    shipments:
                        printifyOrder.shipments?.map((shipment) => ({
                            carrier: shipment.carrier,
                            tracking_number: shipment.number,
                            tracking_url: shipment.url,
                            delivered_at: shipment.delivered_at ?? null,
                        })) ?? [],

                    // Printify Connect (if applicable)
                    printify_connect: printifyOrder.printify_connect || null,
                });
                return;
            } catch (err) {
                console.error("Error fetching order status:", err);
                sendError(res, 500, PRINTIFY_ERRORS.FAILED_ORDER_STATUS);
                return;
            }
        },
    };
};
